restarts from latest output file

diff --git a/autorun/autorun b/autorun/autorun
--- a/autorun/autorun
+++ b/autorun/autorun
@@ -15,13 +15,13 @@
 
 email="vpuri3@illinois.edu" # email log after queuing
 res="restart0.f00001"       # name of restart file
-rsfx="0.f00002"             # suffix of output file to restart from.
+rsfx="0.f00000"             # suffix of output file to restart from.
                             #      if "0.f00000" then restarts from
                             #      last file in directory.
-bsfx="0.f00001"             # suffix of output file to read budgets from.
+bsfx="0.f00000"             # suffix of output file to read budgets from.
                             #      if "0.f00000" don't read budgets.
 sub="my_nekqsub"            # job submission script
-nnodes="256"                # # of nodes
+nnodes="32"                 # # of nodes
 
 ##-------------------------------------------------------------------------##
 ##-------------------------------------------------------------------------##
@@ -97,10 +97,8 @@ for ((i=1; i<=$njobs; i++)); do
 
     if [ "$findrsfx" = true ]; then
 	echo "finding latest output file in $dir1"            |& tee -a $log
-	rsfx=$(ls -t $dir1/$case"0.f"*)
-	rsfx=$($rsfx)
-	rsfx=${rsfx[0]}
-	rsfx=${rsfx:${#list}-8:8};
+	rsfx=$(ls -t $case"0.f"* | head -1)
+	rsfx=${rsfx:${#rsfx}-8:8}
 	echo "latest output file is $case$rsfx."              |& tee -a $log
     fi
 
@@ -112,7 +110,12 @@ for ((i=1; i<=$njobs; i++)); do
     echo "restarting from $res"                               |& tee -a $log
     head -c 130 $res                                          |& tee -a $log
 
-    if [ "$budgets" != true ]; then
+    if [ $? != 0 ]; then		                      
+	echo "ABORT: something wrong with $dir1/$res."        |& tee -a $log
+	send_log; exit 1
+    fi
+
+    if [ "$budgets" = true ]; then
 	echo "reading budgets from i##$case$bsfx"             |& tee -a $log
 	head -c 130 i01$case$bsfx                             |& tee -a $log
     fi
