added more checks

diff --git a/autorun/autorun b/autorun/autorun
--- a/autorun/autorun
+++ b/autorun/autorun
@@ -59,6 +59,11 @@ for ((i=1; i<=$4; i++)); do
     echo "copying $dir0 to $dir1"                             |& tee -a $log
     cp -r $dir0 $dir1                                         |& tee -a $log
 
+    if [ $? != 0 ]; then		                      
+	echo "ABORT: could not copy $dir0 to $dir1."          |& tee -a $log
+	send_log; exit 1
+    fi
+
     cd  $dir1
 
     echo "removing old logs and updating restart"             |& tee -a $log
@@ -72,6 +77,7 @@ for ((i=1; i<=$4; i++)); do
     head -c 130 i01$case$bsfx                                 |& tee -a $log
 
     echo "compiling..."                                       |& tee -a $log
+    echo "using makenek" $(which makenek)                     |& tee -a $log
     makenek $case                                              &>> /dev/null
 
     if [ ! -f $dir1/nek5000 ]; then
@@ -110,11 +116,10 @@ for ((i=1; i<=$4; i++)); do
 	echo "ABORT: job died before its time."               |& tee -a $log
 	echo "appending tail of logfile to run.log"           |& tee -a $log
 	tail -c 1000 $dir1/logfile                                   >> $log
-	send_log
-	exit 1
+	send_log; exit 1
     fi
 
-    echo "goodnight"                                          |& tee -a $log
+    echo "all is good. goodnight."                            |& tee -a $log
     send_log
     sleep 7000
     echo $(date -R)                                           |& tee -a $log
