cleaned

diff --git a/autorun/autorun b/autorun/autorun
--- a/autorun/autorun
+++ b/autorun/autorun
@@ -27,8 +27,7 @@
 
 ##-------------------------------------------------------------------------##
 ##-------------------------------------------------------------------------##
-[ ! -f ./run.conf ] && echo "ABORT: no run.conf found.";
-[   -f ./run.conf ] && echo "run.conf found."; source run.conf;
+[ -f ./run.conf ] && source run.conf || exit 1
 
 case=$1
 base=$2
@@ -42,171 +41,150 @@ log=$dir/run.log
 
 function send_log { mail -s "$case autorun" $email < $log; }
 
+function abort {
+    echo "ABORT:" "$msg" |& tee -a $log
+    send_log; exit 1
+}
+
 if [ ! -f $log ]; then
     touch $log
 fi
 						              
-echo "######################################################" |& tee -a $log
-echo "######################################################" |& tee -a $log
-echo "######################################################" |& tee -a $log
-echo $(date -R)                                               |& tee -a $log
-echo "Starting new session in directory $dir."                |& tee -a $log
-echo "Running case $case from $base$num $njobs times."        |& tee -a $log
-echo "Storing log in $log."                                   |& tee -a $log
+echo "######################################################"     |& tee -a $log
+echo "######################################################"     |& tee -a $log
+echo "######################################################"     |& tee -a $log
+echo $(date -R)                                                   |& tee -a $log
+echo "Starting new session in directory $dir."                    |& tee -a $log
+echo "Running case $case from $base$num $njobs times."            |& tee -a $log
+echo "Storing log in $log."                                       |& tee -a $log
 #
-echo "from run.conf:"                                         |& tee -a $log
-echo "email  is $email"                                       |& tee -a $log
-echo "res    is $res"                                         |& tee -a $log
-echo "rsfx   is $rsfx"                                        |& tee -a $log
-echo "bsfx   is $bsfx"                                        |& tee -a $log
-echo "sub    is $sub"                                         |& tee -a $log
-echo "nnodes is $nnodes"                                      |& tee -a $lo
-echo "fresh is $fresh"                                        |& tee -a $log
+echo "from run.conf:"                                             |& tee -a $log
+echo "email  is $email"                                           |& tee -a $log
+echo "res    is $res"                                             |& tee -a $log
+echo "rsfx   is $rsfx"                                            |& tee -a $log
+echo "bsfx   is $bsfx"                                            |& tee -a $log
+echo "sub    is $sub"                                             |& tee -a $log
+echo "nnodes is $nnodes"                                          |& tee -a $log
+echo "fresh  is $fresh"                                           |& tee -a $log
 #
 findrsfx=false
 if [ "$rsfx" = "0.f00000" ]; then
     findrsfx=true
-    echo "rsfx=$rsfx. Restart from last output file."         |& tee -a $log
+    echo "rsfx=$rsfx. Restart from last output file."             |& tee -a $log
 fi
 
 budgets=true
 if [ "$bsfx" = "0.f00000" ]; then
     budgets=false
-    echo "bsfx=$bsfx. No budgets."                            |& tee -a $log
+    echo "bsfx=$bsfx. No budgets."                                |& tee -a $log
 fi
 
 for ((i=1; i<=$njobs; i++)); do
-    echo "#------------------------------------------------#" |& tee -a $log
-    echo "#------------------ RUN $i ----------------------#" |& tee -a $log
-    echo "#------------------------------------------------#" |& tee -a $log
-    echo $(date -R)                                           |& tee -a $log
+    echo "#------------------------------------------------#"     |& tee -a $log
+    echo "#------------------ RUN $i ----------------------#"     |& tee -a $log
+    echo "#------------------------------------------------#"     |& tee -a $log
+    echo $(date -R)                                               |& tee -a $log
 
+#===============================================================================
 #   Organization
+#===============================================================================
     dir0=$dir/$base$num
     if [ $i = 1 ]; then
 	dir1=$dir0
-	echo "starting from $dir1"                            |& tee -a $log
+	echo "starting from $dir1"                                |& tee -a $log
     else
 	num=$((num+1))
 	dir1=$dir/$base$num
 
-#	checks
-	if [ ! -f $dir0/$case$"0.f00001" ]; then
- 	    echo "ABORT: $dir0 does not have output files."   |& tee -a $log
- 	    send_log; exit 1
-	fi
-	if [ "$budgets" = true ]; then
-	    if [ ! -f $dir0/i01$case$bsfx ]; then
- 		echo "ABORT: no i01$case$bsfx in $dir0."      |& tee -a $log
- 		send_log; exit 1
-	    fi
-	fi
-
 #	copying directories.
-	echo "copying $dir0 to $dir1"                         |& tee -a $log
-	cp -r $dir0 $dir1                                     |& tee -a $log
-	if [ $? != 0 ]; then		                  
-	    echo "ABORT: error in copying $dir0 to $dir1."    |& tee -a $log
-	    send_log; exit 1
-	fi
-
-#       echo "changing write permissions for $dir0"           |& tee -a $log
-#       cd $dir0
-#       for f in $dir0; do # de-link
-#           [ -L "$f" ] && cp --remove-destination "$(readlink "$f")" "$f"]
-#       done
-#       chmod -wx $dir0                                       |& tee -a $log
-    
+	echo "copying $dir0 to $dir1"                             |& tee -a $log
+	cp -r $dir0 $dir1                                         |& tee -a $log
+        [ $? != 0 ] && msg="cant cp $dir1 -> $dir0" && abort
     fi
 
     cd  $dir1
 
+#===============================================================================
 #   updating restart
-    echo "removing old logs and updating restart"             |& tee -a $log
+#===============================================================================
+    echo "removing old logs and updating restart"                 |& tee -a $log
     rm *.cobaltlog *.error *.output *log* *out*
-    # get restart suffix
-    if [ "$findrsfx" = true ]; then
-	echo "finding latest output file in $dir1"            |& tee -a $log
-	rsfx=$(ls -t $case"0.f"* | head -1)
-	rsfx=${rsfx:${#rsfx}-8:8}
-	echo "latest output file is $case$rsfx."              |& tee -a $log
+
+    if [ "$fresh" = false ]; then
+        if [ ! -f $dir0/$case$"0.f"* ]; then
+            msg="$dir0 does not have output files"; abort
+        fi
+        # get restart suffix
+        if [ "$findrsfx" = true ]; then
+            echo "finding latest output file in $dir1"            |& tee -a $log
+            rsfx=$(ls -t $case"0.f"* | head -1)
+            rsfx=${rsfx:${#rsfx}-8:8}
+            echo "latest output file is $case$rsfx."              |& tee -a $log
+        fi
+
+        mv -v $case$rsfx $res                                     |& tee -a $log
+
+        rm $case"0.f"*
+    else
+	fresh=false
     fi
 
-    if [ $i = 1 ]; then
-        # switching restart file to $res
-	[ "$fresh" == false ] &&   mv -v $case$rsfx $res      |& tee -a $log
-    fi
+#===============================================================================
+#   checks
+#===============================================================================
+    echo "restarting from $res"                                   |& tee -a $log
+    head -c 130 $res                                              |& tee -a $log
 
-    if [ ! $i = 1 ]; then
-            # switching restart file to $res
-	mv -v $case$rsfx $res                                 |& tee -a $log
-    fi
-
-    rm $case"0.f00"*
-    echo "restarting from $res"                               |& tee -a $log
-    head -c 130 $res                                          |& tee -a $log
-
-# check
-    if [ $? != 0 ]; then		                      
-	echo "ABORT: something wrong with $dir1/$res."        |& tee -a $log
-	send_log; exit 1
-    fi
-    echo -e "\n"                                              |& tee -a $log
+    [ $? != 0 ] msg="problem with $res" && abort
+    echo -e "\n"                                                  |& tee -a $log
     if [ "$budgets" = true ]; then
-	echo "reading budgets from i##$case$bsfx"             |& tee -a $log
-	head -c 130 i01$case$bsfx                             |& tee -a $log
-	echo -e "\n"                                          |& tee -a $log
-    fi
+        echo "reading budgets from i##$case$bsfx"                 |& tee -a $log
+        head -c 130 i13$case$bsfx                                 |& tee -a $log
+        [ $? != 0 ] msg="problem with i13$case$bsfx" && abort
+        echo -e "\n"                                              |& tee -a $log
+     fi
+
+#===============================================================================
 # compiling
-    echo "compiling..."                                       |& tee -a $log
-    echo "using makenek " $(which makenek)                    |& tee -a $log
-    makenek $case                                              >>  /dev/null
-
-    if [ ! -f $dir1/nek5000 ]; then
-	echo "ABORT: compilation failed in $dir1 ."           |& tee -a $log
-	echo "appending compiler.out to log."                 |& tee -a $log
-	$dir1/compiler.out                                           >> $log
-	send_log; exit 1
-    fi						       
-						       
-    echo "compilation successful."                            |& tee -a $log
-    ./$sub $case $nnodes                                      |& tee -a $log
-					                      
-    if [ $? != 0 ]; then
-	echo "ABORT: could not queue job."                    |& tee -a $log
-	send_log; exit 1
+#===============================================================================
+    if [ $i = 1]; then
+    	echo "compiling..."                                       |& tee -a $log
+    	echo "using makenek " $(which makenek)                    |& tee -a $log
+    	makenek $case                                              >>  /dev/null
+        [ ! -f $dir1/nek5000 ] && msg="compilation failed" && abort
+        echo "compilation successful"                             |& tee -a $log
     fi
 
-    echo "successfully queued job"                            |& tee -a $log
+#===============================================================================
+#   queuing and running
+#===============================================================================
+    ./$sub $case $nnodes                                          |& tee -a $log
+    [ $? != 0 ] &&msg="could not queue job" && abort
+    echo "successfully queued job"                                |& tee -a $log
     sleep 10
-    qstat --header JobId:User:RunTime:WallTime:State:Location |& tee -a $log
+    qstat --header JobId:User:RunTime:WallTime:State:Location     |& tee -a $log
 
-#   waiting in queue
     sleep 60
     j=0
     while [ ! -f $dir1/logfile ]; do
-	echo "waiting in queue"                               |& tee -a $log
-	qstat --header JobId:RunTime:State:Location -u $me    |& tee -a $log
-
+	echo "waiting in queue"                                   |& tee -a $log
+	qstat --header JobId:RunTime:State:Location -u $me        |& tee -a $log
 	j=$((j+1))
-	[ "$j" -gt 20 ] && send_log; exit 1;
+	[ "$j" -gt 20 ] && msg="spent 60 mins in queue" && abort
 	sleep 300
     done
    
-    echo "job is running"                                     |& tee -a $log
+    echo "job is running"                                         |& tee -a $log
  
     sleep 300
     dead=$(tail logfile)
     if echo $dead | grep -Fq "dying"; then
-	echo "ABORT: job died before its time."               |& tee -a $log
-	echo "appending tail of logfile to run.log"           |& tee -a $log
-	tail -c 1000 $dir1/logfile                            |& tee -a $log
-	send_log; exit 1
+	msg="job died before its time"; abort
     fi
 
-    echo "all is good. goodnight."                            |& tee -a $log
+    echo "all is good. goodnight."                                |& tee -a $log
     send_log
-    sleep $simTime
-    echo $(date -R)                                           |& tee -a $log
-    [ ! $i = $njobs ] && echo "long time no see?"             |& tee -a $log
+    sleep $(simTime-300)
+    echo $(date -R)                                               |& tee -a $log
+    [ ! $i = $njobs ] && echo "long time no see?"                 |& tee -a $log
 done
